### ISSUE TITLE
Trying to get k8s-zabbix running on K3s :)

### ISSUE THREAD

**Issue by rbuffi** [zabbix-tooling/k8s-zabbix#2]
Hello,

I'm trying to use your great project to monitor my K3s environment but I do not get all metrics to Zabbix yet.
What I did was:

- Import k8s-zabbix template in Zabbix
- Create Zabbix host k3scluster01 and attach template
- git clone https://github.com/zabbix-tooling/k8s-zabbix
- Modify config_default.py (see below)
- Modify kubernetes\deployment.yaml (see below)
- Build the Docker file for ARM and push it to my private registry with the following command:
docker buildx build --platform linux/arm/v7 -t containerregistrydcsl.azurecr.io/monitoring/k8s-zabbix --push .
- Create the deployment
kubectl create -f kubernetes/deployment.yaml -n zabbix

I see some data (Components, Global, Services, Nodes) in zabbix when I look at latest data for host k3scluster01.
But a lot of data is missing (containers,deployments,etc)

With debugging on I see the folowing errors for the k8s-zabbix pod:

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 371, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 397, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.0.200', port=6443): Max retries exceeded with url: /api/v1/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/app/k8s_zabbix_base/timed_threads.py", line 35, in run
    getattr(self.daemon, self.daemon_method)(self.resource)
  File "/app/k8s_zabbix_base/daemon_thread.py", line 394, in resend_data
    self.send_to_web_api(resource, obj, 'ADDED')
  File "/app/k8s_zabbix_base/daemon_thread.py", line 540, in send_to_web_api
    api = self.get_web_api()
  File "/app/k8s_zabbix_base/daemon_thread.py", line 236, in get_web_api
    self._web_api = WebApi(self.web_api_host, self.web_api_token, verify_ssl=self.web_api_verify_ssl)
  File "/app/k8s_zabbix_base/web_api.py", line 16, in __init__
    r = requests.head(url)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 104, in head
    return request('head', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.0.200', port=6443): Max retries exceeded with url: /api/v1/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

**Comment by rbuffi** [comment]
Here are my config_default.py:

k8s_api_host = 'https://192.168.0.200:6443'
k8s_api_token = 'I removed the data'
verify_ssl = False
debug = True
debug_k8s_events = True
resources_exclude = []

zabbix_server = 'zabbix-server'
zabbix_resources_exclude = ["statefulsets", "daemonsets"]
zabbix_host = 'k3scluster01.dcsl.local'
zabbix_debug = True
zabbix_single_debug = False
zabbix_dry_run = False

web_api_enable = False
web_api_resources_exclude = ["daemonsets", "components", "services", "statefulsets"]
web_api_verify_ssl = False
web_api_host = "'192.168.0.200:6443'"
web_api_token = "I removed the data"
web_api_cluster = 'default'

discovery_interval_fast = 60 * 15
resend_data_interval_fast = 60 * 2

discovery_interval_slow = 60 * 60 * 2
resend_data_interval_slow = 60 * 30

deployment.yaml:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-kubernetes
  namespace: zabbix
spec:
  selector:
    matchLabels:
      app: zabbix-kubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: zabbix-kubernetes
    spec:
      containers:
        - name: k8s-zabbix
          # add your
          #image: your-repo.foo.bar:k8s-zabbix:latest
          image: containerregistrydcsl.azurecr.io/monitoring/k8s-zabbix:latest
          args: [ "config_default" ]
          # review config_default.py for additionaol configuration values (convert the names to uppercase)
          env:
             # the ingress hostname where you can reach the k8s api
             - name: "K8S_API_HOST"
               value: "https://192.168.0.200:6443/"
             # the k8s api token, where you can fetch information from the k8s cluster
             - name: "K8S_API_TOKEN"
               value: "I removed the data"
             - name: "ZABBIX_SERVER"
               value: "zabbix-server"
             # the abstract/virtual host which is configured in zabbix to hold and alert k8s zabbix
             - name: "ZABBIX_HOST"
               value: "k3scluster01.dcsl.local"
             # Enable the optional management api status submission
             - name: "WEB_API_ENABLE"
               value: "False"
             # The base uri of the anagement api status submission
             - name: "WEB_API_HOST"
               value: "https://192.168.0.200:6443/api/v1"
             # The security token for management api status submission
             - name: "WEB_API_TOKEN"
               value: "I removed the data"
             # The name of the k8s cluster in the management system
             - name: "web_api_cluster"
               value: "k3scluster01"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      imagePullSecrets:
      - name: containerregistrydcsl.azurecr.io

**Comment by scoopex** [comment]
I strongly recommend to communicate with the k8s-api by using a ingress because this provides better reliability of the k8s-zabbix monitoring. If a controller node is not available because of a outage or maintenance it might be confusing if the entire cluster cannot be not monitored anymore.

But I also ran in that problem while testing :-)
I my case the problem was originated in the value of "VERIFY_SSL" which was submitted as a string as a environment variable.

With https://github.com/zabbix-tooling/k8s-zabbix/commit/cf6b5cc67fea93c9f93b277ff37f1aac253e9515 string values of toggles are converted automatically to boolean values.

Please reopen, if your problem still remains.

**Comment by rbuffi** [comment]
Thank you very much!
The reason I did not create an ingress is because k3s does not have an kube-api pod, I think it's integrated on the master nodes and I don't know how to expose it as an ingress. Anyway your fix was the solution for the VERIFY_SSL issue and now i'm seeing 187 items in "latest data". The only thing is that items for containers ("Custom - Service - Kubernetes - Containers ") are not having any data. Have you got an idea what's the reason for this?

Thanks again!

**Comment by lalitlsg** [comment]
hi @rbuffi , did template custom_service_kubernetes.xml worked for you.I am getting below error while importing it in zabbix server.
![Screenshot at 22-06-08](https://user-images.githubusercontent.com/45810890/92561091-27cac000-f291-11ea-97c3-8f10455d120c.png)
