### ISSUE TITLE
while testing ./check_kubernetesd configd_c1 gives following error

### ISSUE THREAD

**Issue by lalitlsg** [zabbix-tooling/k8s-zabbix#4]
ERROR : CheckKubernetesDaemon - failed to sent 8 zabbix items, processed 0 items [deployments: coredns]
 ERROR : CheckKubernetesDaemon - failed to sent 8 zabbix items, processed 0 items [deployments: controller]
ERROR : CheckKubernetesDaemon - failed to sent 8 zabbix items, processed 0 items [deployments: request-management-service]
ERROR : CheckKubernetesDaemon - failed to sent 8 zabbix items, processed 0 items [deployments: mongo-request]
 ERROR : CheckKubernetesDaemon - failed to sent 8 zabbix items, processed 0 items [deployments: mongo-vcenter]
ERROR : CheckKubernetesDaemon - failed to sent 8 zabbix items, processed 0 items [deployments: vcenter-deployment]
ERROR : CheckKubernetesDaemon - failed to sent 8 zabbix items, processed 0 items [deployments: metrics-grafana]
 ERROR : CheckKubernetesDaemon - failed to sent 8 zabbix items, processed 0 items [deployments: metrics-kube-state-metrics]
 ERROR : CheckKubernetesDaemon - failed to sent 8 zabbix items, processed 0 items [deployments: metrics-prometheus-operato-operator]

**Comment by scoopex** [comment]
It seems that the ZABBIX_HOST environment variable does not match to the host configured in zabbix.

Improved documentation: https://github.com/zabbix-tooling/k8s-zabbix/blob/master/README.md

**Comment by lalitlsg** [comment]
ok will check it, thanks for the response.
