### ISSUE TITLE
Cannot create item: item with the same key **** already exists

### ISSUE THREAD

**Issue by Xeiro** [zabbix-tooling/k8s-zabbix#6]
Hello, 

we do have a problem with Containers discovery "check_kubernetesd[discover,containers]". In the Info section we can see a lot of messages like this:

Cannot create item: item with the same key "check_kubernetesd[get,containers,cattle-system,agent,agent,not_ready]" already exists.

This problem exists only in Containers discovery. Everything else works without problems. And btw item "check_kubernetesd[get,containers,cattle-system,agent,agent,restart_count]" is successfully created, but has no data.

Do you have any idea what could cause those duplicates?

Thanks

**Comment by scoopex** [comment]
I am sorry, discovery of containers were not really used in my last setup. 
@blodone do you currently use that?

I suppose that there is a simple problem with the generation of the item key (uniqueness).
Pull requests are very welcome for this project.

I suppose that i will start in a few weeks to use this project in my new environment and then i will have a look for that.

**Comment by blodone** [comment]
Hi, i do not experience such messages. Where do you see those messages? Are there similiar named containers in the same namespace?

**Comment by Xeiro** [comment]
> Hi, i do not experience such messages. Where do you see those messages? Are there similiar named containers in the same namespace?

Hello, please take a look at this [screenshot](https://imgshare.io/image/pixToQ) from our Zabbix. There might be similarly named containers in the same namespace, but I suppose it should be no problem until they are exactly the same :).

**Comment by scoopex** [comment]
Your screenshot obviously shows that there are duplicates.
Can you run "check_kubernetesd" locally with a activated "zabbix_debug" and show us the content of the submitted discovery item "check_kubernetesd[discover,containers]"?

**Comment by Xeiro** [comment]
Hello, sorry for the delay. You can download log [here.](https://www.mediafire.com/file/32k0lt6hk5wy72h/k8s-cut.log/file). Thanks for your help!

**Comment by scoopex** [comment]
I currently reimplement this functionality completely . Therefore i close this issue.
