### ISSUE TITLE
Metrics don't show

### ISSUE THREAD

**Issue by blondviper** [zabbix-tooling/k8s-zabbix#8]
Hi, I would like to get some help. I have a microk8s cluster and would like to monitor node status. 

First I imported Custom - Service - Kubernetes.xml to Zabbix and attached it to microk8s cluster nodes. 
Custom - Service - Kubernetes -Services appeared in the latest data with 2 items: Number of ingress services and Number of services. None of these items are reporting data. --> What do I need to do to start getting info about it?
Custom - Service - Kubernetes - Global appears in Latest data with 2 items: 
1. Cluster API Monitoring Heartbeat - sometimes reports hudge number like 16830349348 --> what does it mean if you can explain, please?
2. Cluster Send Items - doesn't report any data to Dashboard --> what are the steps to get this working?

Currently on my Dashboard, I have a Warning from each node saying: "Cluster Discovery" with "UNKNOWN" operational data. 
I have deployed ingress-apiserver but commented out the following three lines because otherwise, it throws errors related to the backend:
`  backend:
    serviceName: kube-apiserver
    servicePort: 443`

Must varible K8S_API_SERVER contain the value of kube-apiserver that I get with the command `k cluster-info` (i.e. K8S_API_SERVER = https://192.168.21.12:16443/api/v1/namespaces/kube-system/services/https:kube-apiserver:ssl/proxy) or I can put dns name I made; apiserver.mydomain.com?

I think this template would really benefit in monitoring the cluster, but I am still new to everything and with some help, I could get it working.

**Comment by scoopex** [comment]
Is outdated or obsolete. Please reopen if it still appears.
