### ISSUE TITLE
Pods created by job trigger two warnings when terminated

### ISSUE THREAD

**Issue by unixfox** [zabbix-tooling/k8s-zabbix#9]
A Pod that finish itself successfully will be in state terminated. k8s-zabbix thinks that the Pod is not in a ready state and report the terminated state as an error.

From the zabbix dashboard, the two warnings:
```
k8s-cluster	Pod database / oracle-db-backup-27109860-8bmzq - status - ERROR: terminated
k8s-cluster	Pod database / oracle-db-backup-27109860-8bmzq - not ready pods for 30minutes
```
From kubectl:
```
NAME                              READY   STATUS      RESTARTS   AGE   IP         
oracle-db-backup-27109920-8bmzq   0/2     Completed   0          31m   10.10.8.218
```

**Comment by scoopex** [comment]
We haven't used jobs in our environments very much. Therefore the support for that was not in the scope of this tool.
Contributions are very welcome.

**Comment by scoopex** [comment]
I currently reimplement this functionality completely . Therefore i close this issue.
